### ISSUE TITLE
MergeFile does not  support UTF-8 with BOM encoded files

### ISSUE THREAD

**Issue by grock90** [webmd-health-services/Whiskey#318]
**Title:** When a function file is saved using UTF-8 with BOM encoding and the Whiskey MergeFile tasks is utilized, the merge file will contain a invalid character and create an invalid .pms1 file. 

**Steps to Repo**:
1.  Create a function file and save it into the .\Functions folder with UTF-8 with BOM encoding
2.  Configure Whiskey.yml file to include the -MergeFile Option
3.  Execute the .\Arc\Build.ps1 and observe the following error displayed

**Actual Error:** 
The term '‹¯¨function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

![image](https://user-images.githubusercontent.com/1671739/70933986-c6bbd780-1ff1-11ea-8f44-a76d034ed9df.png)

**Comment by splatteredbits** [comment]
Determining the encoding of files is very complicated. Getting files to match is even more so. It is user responsibility to make sure the files they are merging can be merged successfully. (See https://devblogs.microsoft.com/oldnewthing/20040324-00/?p=40093 for some example on how just a few encodings work and the challenge in detecting each.)
