### ISSUE TITLE
Create OnlyDuring common task property

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#73]
Create a common `OnlyDuring` common task property that defines a list of what mode the task should run. By default, if not set, it should always run. It can be one or more of `Clean`, `Initialize`, or `Build`. If being run in one of those modes, and a task has the `OnlyDuring` flag set, it should only run if the current run mode is in the list.

Maybe also add the reverse, too, an `ExceptDuring` property.

**Comment by jlariono** [comment]
Completed via #94
